#!/usr/bin/env bash
# Install Nginx and the init file have only a message

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
