#!/usr/bin/env bash
# Install Nginx and the init file have only a message

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

#testing nginx config
sudo nginx -t

sudo service nginx reload
