#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

sudo apt-get update
sudo apt-get install -y nginx

#Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
string_for_replacement='server_name _;\n\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/'

sudo sed -i "s/server_name _;\$/${string_for_replacement}" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http response header

sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service restart nginx
