#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  gideon_frontend
        bind *:80
        mode http
        default_backend gideon_backend
backend gideon_backend
        balance roundrobin
        server 188496-web-01 52.201.221.86:80 check
        server 188496-web-02 34.232.68.230:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
-- INSERT --                                               21,42         All
