#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

count=1

while true
do
  case $count in
    4)
      echo "4 bad luck from China"
      ;;
    9)
      echo "9 bad luck from Japan"
      ;;
    17)
      echo "17 bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  if [ $count -eq 20 ]
  then
    break
  fi
  count=$((count+1))
done
